# Generated by Django 3.2 on 2023-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='condicion_pago',
            field=models.CharField(max_length=600),
        ),
    ]
