# Generated by Django 3.2 on 2023-08-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_proforma_condicion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='condicion_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pago'),
        ),
    ]
